### ISSUE TITLE
Add new Starter Kits

### ISSUE THREAD

**Issue by Tamijo-Netrunner** [andrelind/lbn-core#11]
https://cdn.discordapp.com/attachments/641704002731507732/1109213044069900370/IMG_3683.jpg

https://cdn.discordapp.com/attachments/641704002731507732/1109213044376088606/IMG_3684.jpg

I appreciate these aren't out yet which is probably the main reason they're missing, but adding this here so it is easily accessible for when the time comes.

**Comment by Tamijo-Netrunner** [comment]
Included Upgrades

https://media.discordapp.net/attachments/766771192405164033/1110696608766632067/IMG_0132.jpg

https://media.discordapp.net/attachments/766771192405164033/1110698289013194895/IMG_3696.jpg

**Comment by andtrobs** [comment]
Any sign of the new starter packs, battle of yavin and siege of corusant being avaialble to add to collection?

**Comment by andrelind** [comment]
The starter kits have been added :)
