### ISSUE TITLE
Battle of Yavin/Siege of Coruscant do not appear in collection builder

### ISSUE THREAD

**Issue by johncoxon** [andrelind/lbn-core#26]
I think they should be added to `core.ts`, but I'm not sure what the `ffg` key means in that file. I assumed initially it was the SWZ code, but that doesn't seem to be accurate (e.g. the Never Tell Me the Odds pack has `ffg: 48` but is SWZ64). André, if you let me know what that key means, I can add the two and make a pull request.

**Comment by andrelind** [comment]
You can put whatever in the ffg prop, its an old remnant from the FFG API when I pulled the data from them :)

**Comment by johncoxon** [comment]
Fixed in #27
